Experiment_name: TestMyArch
#mode
mode:
    name: 'cpu'
    ids: [0,1,2,3]

#define dataloader
dataset:
    name: MNIST
    root_path: ../data
    train_dataset:
        args:
            batch_size: 16
    val_dataset:
        args:
            batch_size: 16

#define model
model:
  name: MNIST

#Training
epoch_max: 10
epoch_val: 1
epoch_save: 2
optimizer:
  name: adam
  args:
    lr: 0.0001
    momentum: 0.5